cache:
  directories:
    - ~/.conan/
env:
   global:
     - CONAN_REFERENCE: "USD/20.08"
     - CONAN_USERNAME: "user"
     - CONAN_LOGIN_USERNAME: "user"
     - CONAN_CHANNEL: "channel"
     
linux: &linux
   os: linux
   dist: bionic
   language: python
   python: "3.7"
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9

      - <<: *linux
        env: CONAN_GCC_VERSIONS=5

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6

      - <<: *linux
        env: CONAN_GCC_VERSIONS=7

      - <<: *linux
        env: CONAN_GCC_VERSIONS=8

      - <<: *osx
        osx_image: xcode11
        env: CONAN_APPLE_CLANG_VERSIONS=11.0

      - <<: *osx
        osx_image: xcode10
        env: CONAN_APPLE_CLANG_VERSIONS=10.0

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
