env:
   global:
     - CONAN_REFERENCE: "USD/20.08"
     - CONAN_USERNAME: "latios96"
     - CONAN_LOGIN_USERNAME: "latios96"
     - CONAN_CHANNEL: "channel"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/latios96/my_conan"
     
linux: &linux
   os: linux
   dist: bionic
   language: python
   python: "3.7"
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_BUILD_TYPES=Release CONAN_USD_SHARED=FALSE

      - <<: *osx
        osx_image: xcode11
        env: CONAN_APPLE_CLANG_VERSIONS=11.0 CONAN_BUILD_TYPES=Release

      - <<: *osx
        osx_image: xcode10
        env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_BUILD_TYPES=Release

      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_BUILD_TYPES=Debug CONAN_USD_SHARED=FALSE

      - <<: *osx
        osx_image: xcode11
        env: CONAN_APPLE_CLANG_VERSIONS=11.0 CONAN_BUILD_TYPES=Debug

      - <<: *osx
        osx_image: xcode10
        env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_BUILD_TYPES=Debug

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
