build: false

environment:
  PYTHON: "C:\Python37-x64"

  CONAN_REFERENCE: "USD/20.08"
  CONAN_USERNAME: "latios96"
  CONAN_LOGIN_USERNAME: "latios96"
  CONAN_CHANNEL: "stable"
  CONAN_UPLOAD: "https://api.bintray.com/conan/latios96/my_conan"

  matrix:
    - job_name: shared-no-imaging-release
      appveyor_build_worker_image: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
    - job_name: shared-no-imaging-debug
      appveyor_build_worker_image: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15


install:
  - C:\Python37-x64\Scripts\pip.exe install conan --upgrade
  - C:\Python37-x64\Scripts\pip.exe install conan_package_tools
  - C:\Python37-x64\Scripts\conan user # It creates the conan data directory
  - C:\Python37-x64\Scripts\conan remote add my_bintray https://api.bintray.com/conan/latios96/my_conan


for:
  -
    matrix:
      only:
        - job_name: shared-no-imaging-release

    test_script:
    - C:\Python37-x64\Scripts\conan create . -o USD:shared=True -o USD:with_imaging=False -s build_type=Release -s compiler.version=%CONAN_VISUAL_VERSIONS% --build missing
    - C:\Python37-x64\Scripts\conan upload USD/20.08@latios96/stable --all -r=my_bintray
  -
    matrix:
      only:
        - job_name: shared-no-imaging-debug

    test_script:
    - C:\Python37-x64\Scripts\conan create . -o USD:shared=True -o USD:with_imaging=False -s build_type=Debug -s compiler.version=%CONAN_VISUAL_VERSIONS% --build missing
    - C:\Python37-x64\Scripts\conan upload USD/20.08@latios96/stable --all -r=my_bintray
